version: '3'
services:
  nginx:
    container_name: proxy
    restart: always
    build: ./client
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    restart: always
    build: ./
    working_dir: /app
    expose:
      - 8080
    volumes:
      - ./:/app
    command: mvn clean spring-boot:run